repos:
  - repo: local

    hooks:
      - id: autoflake
        name: autoflake
        description: "Remove unused imports and variables"
        stages: [commit]
        language: system
        types: [python]
        entry: poetry run autoflake .
        require_serial: true
        always_run: true
        args:
          [
            "--in-place",
            "--recursive",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--ignore-init-module-imports",
          ]

      - id: isort
        name: isort
        description: "Sort python imports"
        stages: [commit]
        language: system
        types_or: [cython, pyi, python]
        args: ["--filter-files"]
        always_run: true
        entry: poetry run isort .
        require_serial: true

      - id: yapf
        name: yapf
        description: "Python code formatter"
        stages: [commit]
        language: system
        types: [python]
        entry: poetry run yapf .
        args: ["--recursive"]
        always_run: true
        require_serial: true
