repos:
  - repo: local

    hooks:
      #   - id: autopep8
      #     name: autopep8
      #     description: "Auto pep8 fixes"
      #     stages: [commit]
      #     language: system
      #     entry: poetry run autopep8 .
      #     require_serial: true
      #     always_run: true
      #     args:
      #       [
      #         "--verbose",
      #         "--in-place",
      #         "--recursive",
      #         "--aggressive",
      #         "--aggressive",
      #         "--ignore=W605",
      #       ]
      #     types: [python]

      - id: autoflake
        name: autoflake
        description: "Remove unused imports and variables"
        entry: poetry run autoflake .
        language: system
        types: [python]
        require_serial: true
        always_run: true
        args:
          [
            "--in-place",
            "--recursive",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--ignore-init-module-imports",
          ]

      - id: isort
        name: isort
        description: "Sort python imports"
        stages: [commit]
        require_serial: true
        language: system
        types_or: [cython, pyi, python]
        args: ["--filter-files"]
        always_run: true
        entry: poetry run isort .

      - id: yapf
        name: yapf
        description: "Python code formatter"
        stages: [commit]
        language: system
        types: [python]
        entry: poetry run yapf
        always_run: true

        #require_serial: true

      # - id: mypy
      #   name: mypy
      #   description: "Static type checking"
      #   stages: [commit]
      #   language: system
      #   entry: poetry run mypy
      #   types: [python]
