repos:
  - repo: local
    hooks:
      - id: autopep8
        name: autopep8
        description: "Auto pep8 fixes"
        stages: [commit]
        language: system
        entry: poetry run autopep8
        args:
          [
            "--verbose",
            "--in-place",
            "--recursive",
            "--aggressive",
            "--aggressive",
            "--ignore=W605",
          ]
        types: [python]

      - id: autoflake
        name: autoflake
        description: "Remove unused imports and variables"
        stages: [commit]
        language: system
        entry: poetry run autoflake
        args:
          [
            "--in-place",
            "--recursive",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--ignore-init-module-imports",
          ]
        types: [python]

      - id: isort
        name: isort
        description: "Sort imports"
        stages: [commit]
        language: system
        entry: poetry run isort
        types: [python]

      - id: black
        name: black
        description: "Black: Python code formatter"
        stages: [commit]
        language: system
        entry: poetry run black
        types: [python]

      - id: mypy
        name: mypy
        description: "Static type checking"
        stages: [commit]
        language: system
        entry: poetry run mypy
        types: [python]
